// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPLHn1GPdPZdNJHE6G_SeS9TedRPKl6IU',
    appId: '1:418713340038:web:024d6efe34d21a04df2907',
    messagingSenderId: '418713340038',
    projectId: 'weather-web-b1e1e',
    authDomain: 'weather-web-b1e1e.firebaseapp.com',
    storageBucket: 'weather-web-b1e1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcpNWZhA4NyUHMLZynrWP95uPpIKeLJS8',
    appId: '1:418713340038:android:5efd4d9c0ffa26c9df2907',
    messagingSenderId: '418713340038',
    projectId: 'weather-web-b1e1e',
    storageBucket: 'weather-web-b1e1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcEySUgzdD9SmE_W0uVYuEfEsGnLclu10',
    appId: '1:418713340038:ios:ae65236bd1bb5a83df2907',
    messagingSenderId: '418713340038',
    projectId: 'weather-web-b1e1e',
    storageBucket: 'weather-web-b1e1e.firebasestorage.app',
    iosBundleId: 'com.example.weatherWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcEySUgzdD9SmE_W0uVYuEfEsGnLclu10',
    appId: '1:418713340038:ios:ae65236bd1bb5a83df2907',
    messagingSenderId: '418713340038',
    projectId: 'weather-web-b1e1e',
    storageBucket: 'weather-web-b1e1e.firebasestorage.app',
    iosBundleId: 'com.example.weatherWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPLHn1GPdPZdNJHE6G_SeS9TedRPKl6IU',
    appId: '1:418713340038:web:ed7184215f212351df2907',
    messagingSenderId: '418713340038',
    projectId: 'weather-web-b1e1e',
    authDomain: 'weather-web-b1e1e.firebaseapp.com',
    storageBucket: 'weather-web-b1e1e.firebasestorage.app',
  );
}
